### ISSUE TITLE
Test suite xfail tracking

### ISSUE THREAD

**Issue by tomwhite** [cubed-dev/cubed-xarray#20]
This is a list of work needed to fix the xfails and TODOs in https://github.com/cubed-dev/cubed-xarray/blob/main/cubed_xarray/tests/test_xarray.py

### Cubed
* [x] https://github.com/cubed-dev/cubed/pull/546
* [ ] https://github.com/cubed-dev/cubed/pull/545
* [ ] https://github.com/cubed-dev/cubed/issues/153
* [ ] https://github.com/cubed-dev/cubed/issues/29

### Xarray
* [x] https://github.com/pydata/xarray/pull/9326

[More to be added over time...]
